import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Wrapper } from '../components/layout/Wrapper'
import {Button, Stack, Text, useColorMode} from '@chakra-ui/react'

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create custom Next.js app</title>
        <meta name="description" content="Generated by Daniel Rebolledo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Wrapper centerContent>
        <Stack spacing={3} mb={5}>
          <Text fontSize='4xl' align='center'>Hey this is just a test 🚧</Text>
          <Text fontSize='2xl' align='center'>{colorMode === 'light' ? 'Do you hate light mode?' : 'Afraid of the dark?'}</Text>
        </Stack>
          <Button onClick={toggleColorMode} variant='secondary'>Change it</Button>
        </Wrapper>
      </main>
    </div>
  )
}

export default Home
